let caseIdx=0, drillIdx=0, wordIdx=0, toeflIdx=0, latestUpgrade='';
let toeflQuiz=[], toeflQuizIdx=0, toeflQuizScore=0, toeflQuizWrong=[], toeflAnswered=false, currentToeflChoices=[];

function openTab(id){document.querySelectorAll('.sec').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');document.querySelector(`[data-tab="${id}"]`)?.classList.add('on');if(id==='report')renderReport();if(id==='drill')renderDrillHistory();if(id==='toefl'){renderToefl();renderToeflHistory();}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));

function setupRecognition(btnId,outId){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$(btnId).onclick=()=>alert('이 브라우저에서는 음성 인식을 사용할 수 없습니다. Chrome에서 열어주세요.');return}const r=new SR();r.lang='en-US';r.continuous=true;r.interimResults=true;let final='';let live=false;r.onstart=()=>$(btnId).classList.add('live');r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t}$(outId).textContent=(final+interim).trim()||'듣고 있습니다...'};r.onend=()=>{live=false;$(btnId).classList.remove('live')};$(btnId).onclick=()=>{if(!live){final='';r.start();live=true}else{r.stop();live=false}}}
setupRecognition('mic','speech');setupRecognition('mbaMic','mbaSpeech');setupRecognition('drillMic','drillSpeech');

function cleanText(t){return t.replace(/\s+/g,' ').trim()}
function speakingUpgrade(t){let n=t;const repl=[[/\ba lot\b/gi,'significantly'],[/\bweird\b/gi,'unexpected'],[/\bI think maybe\b/gi,'One possibility is that'],[/\bI think\b/gi,'I believe'],[/\bshows\b/gi,'suggests'],[/\bgoes up and down\b/gi,'fluctuates'],[/\bbig problem\b/gi,'material issue'],[/\bvery important\b/gi,'critical'],[/\bcan not\b/gi,'cannot'],[/\bdon't know exactly\b/gi,'cannot determine with confidence']];repl.forEach(([a,b])=>n=n.replace(a,b));n=n.replace(/^([a-z])/,(m)=>m.toUpperCase());let p=n;if(!/based on|given|evidence|recommend|primary|key|risk|suggest|conclude/i.test(p))p='Based on the available information, '+p.charAt(0).toLowerCase()+p.slice(1);return {natural:n,pro:p}}

function analyzeSpeech(){const t=cleanText($('speech').textContent);if(!t||/표시됩니다|듣고 있습니다/i.test(t))return alert('먼저 영어로 말해보세요.');const u=speakingUpgrade(t);let score=68+Math.min(18,Math.round(t.split(' ').length/4));if(/because|therefore|however|based on|suggest|evidence/i.test(t))score+=5;score=Math.min(96,score);$('mine').textContent=t;$('natural').textContent=u.natural;$('pro').textContent=u.pro;$('speakScore').textContent=score;$('why').textContent='캐주얼한 표현을 줄이고 논리 관계를 더 분명하게 만들었습니다. 회사 회의나 발표에서는 핵심 주장과 근거가 빨리 보이도록 말하면 더 프로페셔널하게 들립니다.';latestUpgrade=u.pro;state.speaking.push({date:now(),score,text:t,upgrade:u.pro});state.lastDate=now();save('workspeak_v2',state);renderHome()}
function clearSpeech(){$('speech').textContent='말한 영어가 여기에 표시됩니다.'}
function hearUpgrade(){if(!latestUpgrade)return;const u=new SpeechSynthesisUtterance(latestUpgrade);u.lang='en-US';speechSynthesis.speak(u)}
function saveUpgrade(){if(!latestUpgrade)return alert('먼저 답변을 분석해보세요.');if(!state.saved.includes(latestUpgrade))state.saved.unshift(latestUpgrade);save('workspeak_v2',state);renderHome();alert('표현을 저장했습니다.')}

function renderCase(){const c=cases[caseIdx];$('caseCategory').textContent=c.cat;$('caseDifficulty').textContent=c.diff;$('caseTitle').textContent=c.title;$('caseContext').textContent=c.context;$('casePrompt').textContent=c.prompt;$('caseFacts').innerHTML=c.facts.map(f=>`<div class="fact"><strong>${f[0]}</strong><span>${f[1]}</span></div>`).join('');$('mbaFeedbackCard').style.display='none';$('modelWrap').style.display='none';$('mbaSpeech').textContent='MBA 케이스 답변이 여기에 표시됩니다.'}
function nextCase(){caseIdx=(caseIdx+1)%cases.length;renderCase()}
function clearMBA(){$('mbaSpeech').textContent='MBA 케이스 답변이 여기에 표시됩니다.';$('mbaFeedbackCard').style.display='none'}
function scoreCase(){const t=cleanText($('mbaSpeech').textContent);if(!t||/표시됩니다|듣고 있습니다/i.test(t))return alert('먼저 MBA 케이스에 영어로 답변해보세요.');const wc=t.split(/\s+/).length;const hasStructure=/first|second|three|framework|I would start|the question|decision/i.test(t);const hasTrade=/trade.?off|risk|upside|downside|cost|benefit|however|but/i.test(t);const hasDecision=/recommend|I would|I recommend|my view|therefore|I believe we should/i.test(t);const hasEvidence=/because|based on|given|data|fact|economic|margin|revenue|capex|customer|market/i.test(t);const hedge=(t.match(/\bmaybe\b|\bI think\b|\bkind of\b|\bsort of\b/gi)||[]).length;let eng=Math.max(55,Math.min(96,66+Math.round(Math.min(wc,90)/7)+(hasEvidence?5:0)-hedge*2));let str=Math.max(50,Math.min(97,60+(hasStructure?14:0)+(hasDecision?12:0)+(wc>45?7:0)));let jud=Math.max(50,Math.min(97,58+(hasTrade?15:0)+(hasEvidence?12:0)+(hasDecision?7:0)));let exec=Math.max(50,Math.min(97,60+(hasDecision?14:0)+(wc>=35&&wc<=110?9:0)+(hasTrade?5:0)-hedge*2));let overall=Math.round(eng*.25+str*.25+jud*.30+exec*.20);$('rEnglish').textContent=eng;$('rStructure').textContent=str;$('rJudgment').textContent=jud;$('rExec').textContent=exec;$('mbaOverall').textContent=overall;const strong=[];if(hasDecision)strong.push('명확한 recommendation을 제시했습니다.');if(hasTrade)strong.push('한쪽 주장만 하지 않고 핵심 trade-off를 언급했습니다.');if(hasEvidence)strong.push('비즈니스 driver와 근거를 사용했습니다.');if(!strong.length)strong.push('케이스의 핵심 문제에 직접 답했습니다.');$('mbaStrong').textContent=strong.join(' ');const improve=[];if(!hasStructure)improve.push('시작할 때 Decision → Drivers → Trade-off → Recommendation 구조를 먼저 제시해보세요.');if(!hasTrade)improve.push('핵심 downside risk와 trade-off를 명시적으로 말해보세요.');if(!hasDecision)improve.push('분석으로 끝내지 말고 최종 recommendation을 한 문장으로 정리하세요.');if(wc<35)improve.push('결론을 방어할 수 있을 정도의 근거를 조금 더 추가하세요.');if(hedge)improve.push('“I think/maybe”를 줄이고 더 의도적인 표현을 사용하세요.');$('mbaImprove').textContent=improve.length?improve.join(' '):'구조가 좋습니다. 다음에는 핵심 리스크를 수치화하고 recommendation을 더 짧게 압축해보세요.';const c=cases[caseIdx];$('mbaChallenge').textContent=c.challenge;$('mbaModel').textContent=c.model;$('mbaFeedbackCard').style.display='block';state.mba.push({date:now(),score:overall,english:eng,structure:str,judgment:jud,exec,text:t,case:c.title});state.lastDate=now();save('workspeak_v2',state);renderHome();setTimeout(()=>$('mbaFeedbackCard').scrollIntoView({behavior:'smooth',block:'start'}),100)}
function speakChallenge(){const u=new SpeechSynthesisUtterance($('mbaChallenge').textContent);u.lang='en-US';speechSynthesis.speak(u)}
function showModel(){$('modelWrap').style.display='block'}

function renderDrill(){const d=drills[drillIdx];$('drillN').textContent=drillIdx+1;$('drillCat').textContent=d[0];$('drillQ').textContent=d[1];$('drillSpeech').textContent='영어 답변을 말해보세요.';$('drillMine').textContent='—';$('drillNatural').textContent='—';$('drillRef').textContent='먼저 답해보세요.';$('drillPhrase').textContent='—';$('drillWhy').textContent='답변 후 표현을 어떻게 고칠 수 있는지 설명해드립니다.'}
function checkDrill(){const d=drills[drillIdx];const t=cleanText($('drillSpeech').textContent);if(!t||/말해보세요|듣고 있습니다/i.test(t))return alert('먼저 영어로 답변해보세요.');const u=speakingUpgrade(t);$('drillMine').textContent=t;$('drillNatural').textContent=u.natural;$('drillRef').textContent=d[2];$('drillPhrase').textContent=d[3];const changed=u.natural.toLowerCase()!==t.toLowerCase();$('drillWhy').textContent=changed?'원래 의미는 유지하면서 캐주얼하거나 모호한 표현을 더 자연스러운 업무 영어로 바꿨습니다. 오른쪽 추천 답변과 비교해서 문장 구조와 핵심 표현을 가져가세요.':'현재 답변의 기본 구조는 괜찮습니다. 추천 답변과 비교해서 더 간결한 표현과 핵심 phrase를 익혀보세요.';state.drills.unshift({date:now(),index:drillIdx,cat:d[0],prompt:d[1],answer:t,natural:u.natural,reference:d[2],phrase:d[3]});state.lastDate=now();save('workspeak_v2',state);renderDrillHistory();renderHome()}
function nextDrill(){drillIdx=(drillIdx+1)%drills.length;renderDrill()}
function renderDrillHistory(){const list=state.drills||[];$('drillHistoryCount').textContent=`${list.length}개 저장`;$('drillHistory').innerHTML=list.length?list.slice(0,20).map(x=>`<div class="historyItem"><div class="between"><span class="pill">${x.cat}</span><span class="tip">${new Date(x.date).toLocaleDateString('ko-KR')}</span></div><b class="historyPrompt">${x.prompt}</b><div class="historyCompare"><div><span>내 답변</span>${x.answer}</div><div><span>더 자연스럽게</span><b>${x.natural}</b></div><div><span>추천 답변</span>${x.reference}</div></div><div class="tip" style="margin-top:8px">핵심 표현: <b>${x.phrase}</b></div></div>`).join(''):'아직 저장된 답변이 없습니다.'}

function renderWord(){const w=words[wordIdx];$('wordCat').textContent=w[0];$('wordText').textContent=w[1];$('wordMeaning').textContent=w[2];$('wordExample').textContent=w[3];renderBank()}
function rateWord(delta){const key=words[wordIdx][1];state.mastery[key]=Math.max(0,Math.min(100,(state.mastery[key]??40)+(delta>0?20:-15)));save('workspeak_v2',state);wordIdx=(wordIdx+1)%words.length;renderWord();renderHome()}
function renderBank(){$('bank').innerHTML=words.map(w=>{const m=state.mastery[w[1]]??40;return `<div class="bankItem"><div class="between"><b style="font-size:13px">${w[1]}</b><span class="tip">${m}%</span></div><div class="progress" style="margin-top:7px"><i style="width:${m}%"></i></div></div>`}).join('')}

function renderToefl(){const w=toeflWords[toeflIdx];const m=state.toeflMastery[w[0]]??40;$('toeflWord').textContent=w[0];$('toeflMeaning').textContent=w[1];$('toeflSynonym').textContent=w[2];$('toeflExample').textContent=w[3];$('toeflMasteryText').textContent=`숙련도 ${m}%`;renderToeflBank()}
function rateToefl(delta){const key=toeflWords[toeflIdx][0];state.toeflMastery[key]=Math.max(0,Math.min(100,(state.toeflMastery[key]??40)+(delta>0?20:-15)));save('workspeak_v2',state);toeflIdx=(toeflIdx+1)%toeflWords.length;renderToefl();renderHome()}
function renderToeflBank(){const sorted=[...toeflWords].sort((a,b)=>(state.toeflMastery[a[0]]??40)-(state.toeflMastery[b[0]]??40));$('toeflBank').innerHTML=sorted.slice(0,12).map(w=>{const m=state.toeflMastery[w[0]]??40;return `<div class="bankItem"><div class="between"><div><b>${w[0]}</b><div class="tip">${w[1]} · ${w[2]}</div></div><span class="tip">${m}%</span></div><div class="progress" style="margin-top:7px"><i style="width:${m}%"></i></div></div>`}).join('')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startToeflQuiz(){toeflQuiz=shuffle(toeflWords).slice(0,10);toeflQuizIdx=0;toeflQuizScore=0;toeflQuizWrong=[];toeflAnswered=false;$('toeflQuizCard').style.display='block';renderToeflQuizQ();setTimeout(()=>$('toeflQuizCard').scrollIntoView({behavior:'smooth',block:'start'}),100)}
function renderToeflQuizQ(){if(toeflQuizIdx>=toeflQuiz.length)return finishToeflQuiz();const w=toeflQuiz[toeflQuizIdx];$('toeflQuizN').textContent=toeflQuizIdx+1;$('toeflQuizWord').textContent=w[0];$('toeflQuizFeedback').textContent='';toeflAnswered=false;const wrong=shuffle(toeflWords.filter(x=>x[0]!==w[0])).slice(0,3).map(x=>x[1]);currentToeflChoices=shuffle([w[1],...wrong]);$('toeflChoices').innerHTML=currentToeflChoices.map((c,i)=>`<button class="choiceBtn" onclick="answerToefl(this,${i})">${c}</button>`).join('')}
function answerToefl(btn,choiceIdx){if(toeflAnswered)return;toeflAnswered=true;const w=toeflQuiz[toeflQuizIdx];const choice=currentToeflChoices[choiceIdx];const ok=choice===w[1];document.querySelectorAll('.choiceBtn').forEach((b,i)=>{b.disabled=true;if(currentToeflChoices[i]===w[1])b.classList.add('correct')});if(!ok){btn.classList.add('wrong');toeflQuizWrong.push(w[0]);state.toeflMastery[w[0]]=Math.max(0,(state.toeflMastery[w[0]]??40)-10);$('toeflQuizFeedback').textContent=`정답: ${w[1]} · 동의어: ${w[2]}`}else{toeflQuizScore++;state.toeflMastery[w[0]]=Math.min(100,(state.toeflMastery[w[0]]??40)+10);$('toeflQuizFeedback').textContent=`정답! 동의어: ${w[2]}`}save('workspeak_v2',state);setTimeout(()=>{toeflQuizIdx++;renderToeflQuizQ()},850)}
function finishToeflQuiz(){const score=toeflQuizScore*10;state.toeflTests.unshift({date:now(),score,wrong:[...toeflQuizWrong]});state.lastDate=now();save('workspeak_v2',state);$('toeflQuizWord').textContent=`${score}점`;$('toeflChoices').innerHTML=`<div class="callout"><b>10문제 중 ${toeflQuizScore}개 정답</b><br>${toeflQuizWrong.length?`다시 볼 단어: ${toeflQuizWrong.join(', ')}`:'모두 맞았습니다!'}</div>`;$('toeflQuizFeedback').textContent='결과가 저장되었습니다. 주간 리포트에도 반영됩니다.';renderToeflHistory();renderToefl();renderHome()}
function renderToeflHistory(){const t=state.toeflTests||[];$('toeflLastScore').textContent=t.length?`최근 ${t[0].score}점`:'아직 테스트 없음';$('toeflTestHistory').innerHTML=t.length?t.slice(0,5).map(x=>`<div class="historyItem"><div class="between"><b>${new Date(x.date).toLocaleDateString('ko-KR')}</b><span class="pill ${x.score>=80?'green':'amber'}">${x.score}점</span></div><div class="tip">${x.wrong.length?`틀린 단어: ${x.wrong.join(', ')}`:'틀린 단어 없음'}</div></div>`).join(''):'첫 10문제 테스트를 시작해보세요.'}

function sameWeek(dateStr){const d=new Date(dateStr),n=new Date();const monday=x=>{const y=new Date(x);const day=(y.getDay()+6)%7;y.setHours(0,0,0,0);y.setDate(y.getDate()-day);return y};return monday(d).getTime()===monday(n).getTime()}
function avg(a,key='score'){return a.length?Math.round(a.reduce((s,x)=>s+(x[key]||0),0)/a.length):null}
function renderHome(){const ws=state.speaking.filter(x=>sameWeek(x.date)),wm=state.mba.filter(x=>sameWeek(x.date)),wd=state.drills.filter(x=>sameWeek(x.date));$('weekCount').textContent=ws.length;$('mbaCount').textContent=wm.length;$('drillCount').textContent=wd.length;$('toeflHomeScore').textContent=state.toeflTests.length?state.toeflTests[0].score:'—';$('savedHome').innerHTML=state.saved.length?state.saved.slice(0,5).map(x=>`<span class="pill green">${x}</span>`).join(''):'아직 저장한 표현이 없습니다.';let f='프로페셔널한 명확성';if(wm.length&&avg(wm,'structure')<75)f='MBA 케이스 구조화';else if(wm.length&&avg(wm,'judgment')<75)f='비즈니스 판단';else if(ws.length&&avg(ws)<75)f='자연스러운 전달';else if(state.toeflTests.length&&state.toeflTests[0].score<80)f='TOEFL Academic Vocabulary';$('focusText').textContent=f;$('streak').textContent='1일'}
function renderReport(){const ws=state.speaking.filter(x=>sameWeek(x.date)),wm=state.mba.filter(x=>sameWeek(x.date)),wd=state.drills.filter(x=>sameWeek(x.date));$('avgSpeak').textContent=avg(ws)??'—';$('avgMBA').textContent=avg(wm)??'—';$('reportDrills').textContent=wd.length;$('reportToefl').textContent=state.toeflTests.length?state.toeflTests[0].score:'—';const all=[...ws.map(x=>({date:x.date,score:x.score})),...wm.map(x=>({date:x.date,score:x.score}))].sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(-8);$('trend').innerHTML=all.length?all.map(x=>`<i style="height:${Math.max(12,x.score)}%"><span>${x.score}</span></i>`).join(''):'<div class="empty">아직 점수 데이터가 없습니다.</div>';const pats=[];if(ws.length&&avg(ws)<78)pats.push('• 말하기: 핵심 요점을 더 빨리 말하고 casual filler를 줄이세요.');if(wm.length&&avg(wm,'structure')<78)pats.push('• MBA: 세부 내용 전에 답변 구조를 먼저 제시하세요.');if(wm.length&&avg(wm,'judgment')<78)pats.push('• Business judgment: 핵심 trade-off와 downside risk를 명시적으로 말하세요.');if(wm.length&&avg(wm,'exec')<78)pats.push('• Executive presence: 마지막에 하나의 분명한 recommendation으로 끝내세요.');if(state.toeflTests.length&&state.toeflTests[0].score<80)pats.push(`• TOEFL: 최근 틀린 단어를 우선 복습하세요 — ${state.toeflTests[0].wrong.slice(0,5).join(', ')}`);$('patterns').innerHTML=pats.length?pats.join('<br><br>'):'아직 반복되는 약점이 충분히 확인되지 않았습니다.';let plan='이번 주에 말하기 3개, MBA 케이스 2개, 10문장 훈련 10개, TOEFL 단어 테스트 1회를 완료해보세요.';if(pats.length)plan='다음 주: ① 60초 업무 업데이트 3개, ② MBA 케이스 2개, ③ 저장된 10문장 답변에서 수정 표현 5개 다시 말하기, ④ TOEFL 약점 단어 10개 복습 후 10문제 재시험.';$('plan').textContent=plan}

renderCase();renderDrill();renderDrillHistory();renderWord();renderToefl();renderToeflHistory();renderHome();