let caseIdx=0, drillIdx=0, wordIdx=0, latestUpgrade='';

function openTab(id){document.querySelectorAll('.sec').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');document.querySelector(`[data-tab="${id}"]`)?.classList.add('on');if(id==='report')renderReport();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));

function setupRecognition(btnId,outId){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$(btnId).onclick=()=>alert('Chrome speech recognition is not available in this browser.');return}const r=new SR();r.lang='en-US';r.continuous=true;r.interimResults=true;let final='';r.onstart=()=>$(btnId).classList.add('live');r.onend=()=>$(btnId).classList.remove('live');r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t}$(outId).textContent=(final+interim).trim()||'Listening...'};let live=false;$(btnId).onclick=()=>{if(!live){final='';r.start();live=true}else{r.stop();live=false}};r.onend=()=>{live=false;$(btnId).classList.remove('live')}}
setupRecognition('mic','speech');setupRecognition('mbaMic','mbaSpeech');setupRecognition('drillMic','drillSpeech');

function cleanText(t){return t.replace(/\s+/g,' ').trim()}
function speakingUpgrade(t){let n=t;const repl=[[/\ba lot\b/gi,'significantly'],[/\bweird\b/gi,'unexpected'],[/\bI think maybe\b/gi,'One possibility is that'],[/\bI think\b/gi,'I believe'],[/\bshows\b/gi,'suggests'],[/\bgoes up and down\b/gi,'fluctuates'],[/\bbig problem\b/gi,'material issue'],[/\bvery important\b/gi,'critical']];repl.forEach(([a,b])=>n=n.replace(a,b));if(n===t)n=t.replace(/^([a-z])/,(m)=>m.toUpperCase());let p=n; if(!/based on|given|evidence|recommend|primary|key|risk|suggest/i.test(p)) p='Based on the available information, '+p.charAt(0).toLowerCase()+p.slice(1);return {natural:n,pro:p}}
function analyzeSpeech(){const t=cleanText($('speech').textContent);if(!t||/transcript|listening/i.test(t))return alert('Please speak first.');const u=speakingUpgrade(t);let score=68+Math.min(18,Math.round(t.split(' ').length/4));if(/because|therefore|however|based on|suggest|evidence/i.test(t))score+=5;score=Math.min(96,score);$('mine').textContent=t;$('natural').textContent=u.natural;$('pro').textContent=u.pro;$('speakScore').textContent=score;$('why').textContent='The upgrade reduces casual wording, makes the logic explicit, and uses language that sounds more deliberate in technical or leadership discussions.';latestUpgrade=u.pro;state.speaking.push({date:now(),score,text:t,upgrade:u.pro});state.lastDate=now();save('workspeak_v2',state);renderHome()}
function clearSpeech(){$('speech').textContent='Your transcript will appear here.'}
function hearUpgrade(){if(!latestUpgrade)return;const u=new SpeechSynthesisUtterance(latestUpgrade);u.lang='en-US';speechSynthesis.speak(u)}
function saveUpgrade(){if(!latestUpgrade)return alert('Analyze a response first.');if(!state.saved.includes(latestUpgrade))state.saved.unshift(latestUpgrade);save('workspeak_v2',state);renderHome();alert('Saved to your phrase upgrades.')}

function renderCase(){const c=cases[caseIdx];$('caseCategory').textContent=c.cat;$('caseDifficulty').textContent=c.diff;$('caseTitle').textContent=c.title;$('caseContext').textContent=c.context;$('casePrompt').textContent=c.prompt;$('caseFacts').innerHTML=c.facts.map(f=>`<div class="fact"><strong>${f[0]}</strong><span>${f[1]}</span></div>`).join('');$('mbaFeedbackCard').style.display='none';$('modelWrap').style.display='none';$('mbaSpeech').textContent='Your case response will appear here.'}
function nextCase(){caseIdx=(caseIdx+1)%cases.length;renderCase()}
function clearMBA(){$('mbaSpeech').textContent='Your case response will appear here.';$('mbaFeedbackCard').style.display='none'}
function scoreCase(){const t=cleanText($('mbaSpeech').textContent);if(!t||/response|listening/i.test(t))return alert('Please answer the case out loud first.');const wc=t.split(/\s+/).length;const hasStructure=/first|second|three|framework|I would start|the question|decision/i.test(t);const hasTrade=/trade.?off|risk|upside|downside|cost|benefit|however|but/i.test(t);const hasDecision=/recommend|I would|I recommend|my view|therefore|I believe we should/i.test(t);const hasEvidence=/because|based on|given|data|fact|economic|margin|revenue|capex|customer|market/i.test(t);const hedge=(t.match(/\bmaybe\b|\bI think\b|\bkind of\b|\bsort of\b/gi)||[]).length;
 let eng=Math.max(55,Math.min(96,66+Math.round(Math.min(wc,90)/7)+(hasEvidence?5:0)-hedge*2));let str=Math.max(50,Math.min(97,60+(hasStructure?14:0)+(hasDecision?12:0)+(wc>45?7:0)));let jud=Math.max(50,Math.min(97,58+(hasTrade?15:0)+(hasEvidence?12:0)+(hasDecision?7:0)));let exec=Math.max(50,Math.min(97,60+(hasDecision?14:0)+(wc>=35&&wc<=110?9:0)+(hasTrade?5:0)-hedge*2));let overall=Math.round(eng*.25+str*.25+jud*.30+exec*.20);
 $('rEnglish').textContent=eng;$('rStructure').textContent=str;$('rJudgment').textContent=jud;$('rExec').textContent=exec;$('mbaOverall').textContent=overall;
 const strong=[];if(hasDecision)strong.push('You made a clear recommendation.');if(hasTrade)strong.push('You recognized meaningful trade-offs instead of giving a one-sided answer.');if(hasEvidence)strong.push('You grounded the reasoning in business drivers.');if(!strong.length)strong.push('You engaged directly with the business problem.');$('mbaStrong').textContent=strong.join(' ');
 const improve=[];if(!hasStructure)improve.push('Open with a clearer structure: decision → 2–3 drivers → trade-off → recommendation.');if(!hasTrade)improve.push('Explicitly name the key trade-off and downside risk.');if(!hasDecision)improve.push('End with a decisive recommendation rather than only analysis.');if(wc<35)improve.push('Add enough reasoning to make the recommendation defensible.');if(hedge)improve.push('Reduce “I think/maybe” and use more deliberate executive language.');$('mbaImprove').textContent=improve.length?improve.join(' '):'Good structure. Next, make the recommendation even more concise and quantify the key risk where possible.';
 const c=cases[caseIdx];$('mbaChallenge').textContent=c.challenge;$('mbaModel').textContent=c.model;$('mbaFeedbackCard').style.display='block';state.mba.push({date:now(),score:overall,english:eng,structure:str,judgment:jud,exec,text:t,case:c.title});state.lastDate=now();save('workspeak_v2',state);renderHome();setTimeout(()=>$('mbaFeedbackCard').scrollIntoView({behavior:'smooth',block:'start'}),100)}
function speakChallenge(){const u=new SpeechSynthesisUtterance($('mbaChallenge').textContent);u.lang='en-US';speechSynthesis.speak(u)}
function showModel(){$('modelWrap').style.display='block'}

function renderDrill(){const d=drills[drillIdx];$('drillN').textContent=drillIdx+1;$('drillCat').textContent=d[0];$('drillQ').textContent=d[1];$('drillRef').textContent='Complete the prompt first.';$('drillPhrase').textContent='—';$('drillSpeech').textContent='Speak your answer.'}
function checkDrill(){const d=drills[drillIdx];$('drillRef').textContent=d[2];$('drillPhrase').textContent=d[3]}
function nextDrill(){drillIdx=(drillIdx+1)%drills.length;renderDrill()}
function renderWord(){const w=words[wordIdx];$('wordCat').textContent=w[0];$('wordText').textContent=w[1];$('wordMeaning').textContent=w[2];$('wordExample').textContent=w[3];renderBank()}
function rateWord(delta){const key=words[wordIdx][1];state.mastery[key]=Math.max(0,Math.min(100,(state.mastery[key]??40)+(delta>0?20:-15)));save('workspeak_v2',state);wordIdx=(wordIdx+1)%words.length;renderWord();renderHome()}
function renderBank(){$('bank').innerHTML=words.map(w=>{const m=state.mastery[w[1]]??40;return `<div class="bankItem"><div class="between"><b style="font-size:13px">${w[1]}</b><span class="tip">${m}%</span></div><div class="progress" style="margin-top:7px"><i style="width:${m}%"></i></div></div>`}).join('')}

function sameWeek(dateStr){const d=new Date(dateStr), n=new Date();const monday=x=>{const y=new Date(x);const day=(y.getDay()+6)%7;y.setHours(0,0,0,0);y.setDate(y.getDate()-day);return y};return monday(d).getTime()===monday(n).getTime()}
function avg(a,key='score'){return a.length?Math.round(a.reduce((s,x)=>s+(x[key]||0),0)/a.length):null}
function renderHome(){const ws=state.speaking.filter(x=>sameWeek(x.date)), wm=state.mba.filter(x=>sameWeek(x.date));$('weekCount').textContent=ws.length;$('mbaCount').textContent=wm.length;$('masteredCount').textContent=Object.values(state.mastery).filter(v=>v>=80).length;$('savedHome').innerHTML=state.saved.length?state.saved.slice(0,5).map(x=>`<span class="pill green">${x}</span>`).join(''):'No saved phrase upgrades yet.';let f='Professional clarity';if(wm.length&&avg(wm,'structure')<75)f='Case structuring';else if(wm.length&&avg(wm,'judgment')<75)f='Business judgment';else if(ws.length&&avg(ws)<75)f='Natural delivery';$('focusText').textContent=f;const last=state.lastDate?Math.max(1,Math.round((Date.now()-new Date(state.lastDate))/86400000)===0?1:1):1;$('streak').textContent=last+' day'}
function renderReport(){const ws=state.speaking.filter(x=>sameWeek(x.date)),wm=state.mba.filter(x=>sameWeek(x.date));$('avgSpeak').textContent=avg(ws)??'—';$('avgMBA').textContent=avg(wm)??'—';$('totalResponses').textContent=ws.length+wm.length;$('savedCount').textContent=state.saved.length;const all=[...ws.map(x=>({date:x.date,score:x.score})),...wm.map(x=>({date:x.date,score:x.score}))].sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(-8);$('trend').innerHTML=all.length?all.map(x=>`<i style="height:${Math.max(12,x.score)}%"><span>${x.score}</span></i>`).join(''):'<div class="empty">No score data yet.</div>';const pats=[];if(ws.length&&avg(ws)<78)pats.push('• Speaking: make the main point earlier and reduce casual filler.');if(wm.length&&avg(wm,'structure')<78)pats.push('• MBA cases: state a clear structure before diving into details.');if(wm.length&&avg(wm,'judgment')<78)pats.push('• Business judgment: name the core trade-off and downside risk explicitly.');if(wm.length&&avg(wm,'exec')<78)pats.push('• Executive presence: finish with one decisive recommendation.');$('patterns').innerHTML=pats.length?pats.join('<br><br>'):'No recurring weakness has been identified yet.';let plan='Complete at least 3 speaking responses and 2 MBA cases this week so the report can personalize your next curriculum.';if(pats.length)plan='Next week: ① 3 concise work updates under 60 seconds, ② 2 MBA cases using Frame → Drivers → Trade-offs → Decide → Recommend, ③ review 10 phrases including “the most defensible path,” “protect the downside,” and “based on the available evidence.”';$('plan').textContent=plan}

renderCase();renderDrill();renderWord();renderHome();