const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state=load('workspeak_v2',{speaking:[],mba:[],saved:[],mastery:{},lastDate:null});

const cases=[
 {cat:'STRATEGY',diff:'INTERMEDIATE',title:'Scale the Battery Business or Protect Margins?',context:'A battery technology company has strong pilot results but limited manufacturing capacity. A large customer offers a multi-year contract that could triple revenue, but requires major capex and aggressive delivery commitments.',facts:[['$45M','Required capex'],['3×','Potential revenue'],['18 mo','Ramp timeline']],prompt:'Should the company accept the contract now, renegotiate the terms, or walk away? Explain the decision framework, key risks, and your recommendation.',challenge:'The customer says the commercial terms are final and will choose a competitor within two weeks. Does your recommendation change?',model:'I would pursue the contract, but only if we can restructure the risk rather than simply accept it. The upside is strategically meaningful: it validates demand, accelerates scale, and can improve our cost position. The constraint is that the current terms place too much execution and capital risk on us. I would focus the negotiation on milestone-based volume commitments, customer support for tooling or capacity, and a phased ramp. If those protections are unavailable, I would be willing to walk away because one contract should not put the company’s balance sheet at risk.'},
 {cat:'OPERATIONS',diff:'INTERMEDIATE',title:'A Quality Problem Before a Major Launch',context:'Two weeks before a customer launch, field validation shows a 3% failure rate in one subsystem. The engineering team believes a design change can reduce risk, but implementing it would delay launch by six weeks.',facts:[['3%','Observed failures'],['6 wk','Design-change delay'],['$8M','Launch penalty exposure']],prompt:'Would you launch on time, delay for the design change, or choose a containment strategy? What information matters most?',challenge:'The CEO says the customer relationship will be severely damaged by any delay. How would you respond?',model:'I would not frame this as a binary launch-versus-delay decision yet. First, I would quantify severity, detectability, and whether the failure mechanism is bounded. If the failure can create a safety or high-cost field issue, I would delay despite the commercial penalty. If the risk is contained and detectable, I would consider a controlled launch with enhanced screening, limited volume, and a clear retrofit plan. My recommendation would be based on expected downside, not schedule pressure alone.'},
 {cat:'MARKET ENTRY',diff:'ADVANCED',title:'Enter the AI Data Center Power Market?',context:'An energy storage company is evaluating a new product for AI data centers. Demand is growing quickly, but customers require extremely high uptime and fast service response. The company has strong hardware but limited experience selling to data center operators.',facts:[['35%','Market CAGR'],['99.999%','Target uptime'],['2','Established rivals']],prompt:'Should the company enter now, partner first, or wait? Build the case around market attractiveness, capabilities, differentiation, and execution risk.',challenge:'A hyperscaler offers to co-develop the product but wants exclusivity for three years. Would you accept?',model:'I would enter, but through a focused partnership rather than a broad standalone launch. The market is attractive, but reliability expectations and service requirements create a capability gap that hardware strength alone does not solve. A lighthouse customer can accelerate learning and credibility. I would accept co-development only with carefully bounded exclusivity—limited by geography, use case, or volume—so we gain validation without giving up the broader market.'},
 {cat:'PRICING',diff:'INTERMEDIATE',title:'Cut Price to Win a Strategic Customer?',context:'A competitor offers a key customer a 15% lower price. Matching the offer would reduce gross margin substantially, but losing the account could weaken future reference sales.',facts:[['15%','Competitor discount'],['28%','Current gross margin'],['12%','Customer share of revenue']],prompt:'Should you match the price? Discuss customer lifetime value, strategic value, margin discipline, and alternatives to a straight discount.',challenge:'Sales argues this logo is essential for credibility. What non-price concessions would you consider?',model:'I would avoid an automatic price match. The right question is the account’s economic and strategic value relative to the margin we would give up. I would first test whether we can trade price for something valuable—longer commitment, minimum volume, faster payment, reduced customization, or reference rights. If the customer truly improves future win rates, a targeted concession may be justified, but it should purchase strategic value rather than simply defend revenue.'},
 {cat:'LEADERSHIP',diff:'ADVANCED',title:'Your Best Engineer Wants to Leave',context:'A top engineer is critical to a major program but says they are burned out and considering an external offer. Their manager wants to counter with more pay and a promotion immediately.',facts:[['Top 5%','Performance'],['4 mo','Critical milestone'],['1','External offer']],prompt:'How would you handle the situation as the business leader? Balance retention, fairness, organizational health, and execution risk.',challenge:'If you make an exception, other high performers may ask for the same treatment. How do you manage that?',model:'I would treat compensation as only one part of the problem. First I would understand whether the root issue is workload, growth, manager quality, scope, or pay. If this person is truly critical and under-market, a retention adjustment may be warranted, but I would avoid inventing a title solely to stop a resignation. I would pair any retention action with workload correction, succession planning, and a broader check for systemic burnout so the organization is not dependent on one person.'},
 {cat:'CAPITAL ALLOCATION',diff:'ADVANCED',title:'Build In-House or Acquire?',context:'A growing industrial company needs a software capability that is becoming central to its product. Building internally may take two years; acquiring a startup would accelerate the roadmap but costs $120M and brings integration risk.',facts:[['24 mo','Build timeline'],['$120M','Acquisition price'],['18 mo','Competitor lead']],prompt:'Build, buy, or partner? Explain how you would assess strategic control, speed, valuation, integration risk, and long-term capability.',challenge:'The startup founders refuse a long retention package. Does that change your view?',model:'Given the competitor lead, speed has real strategic value, but I would not acquire simply to buy time. I would assess whether the startup owns differentiated technology, talent, or customer access that we cannot reproduce efficiently. If the value depends heavily on the founders and they will not stay, the acquisition thesis weakens materially. In that case, I would favor a partnership or targeted talent and technology build unless the underlying IP is independently durable.'}
];

const drills=[
 ['TECHNICAL','현재 데이터만으로는 root cause라고 단정하기 어렵습니다.','Based on the current data, I would not conclude that this is the root cause yet.','I would not conclude that... yet'],
 ['TECHNICAL','3번째 사이클부터 온도 변동이 더 뚜렷해졌습니다.','The temperature fluctuations became more pronounced beginning in cycle three.','became more pronounced'],
 ['TECHNICAL','이 가설을 확인하려면 추가 실험이 필요합니다.','We need additional testing to validate this hypothesis.','validate this hypothesis'],
 ['BUSINESS','이 결정은 비용과 실행 속도 사이의 trade-off입니다.','This decision involves a trade-off between cost and speed of execution.','a trade-off between A and B'],
 ['MBA','시장 규모보다 지속 가능한 경쟁우위가 더 중요합니다.','A sustainable competitive advantage matters more than market size alone.','sustainable competitive advantage'],
 ['LEADERSHIP','저는 그 결론에 완전히 동의하지 않지만 우려가 어디서 나오는지는 이해합니다.','I do not fully agree with that conclusion, but I understand the concern behind it.','I understand the concern behind it'],
 ['LEADERSHIP','먼저 우리가 해결하려는 문제에 합의했으면 합니다.','I would like us to align on the problem we are trying to solve first.','align on the problem'],
 ['EXECUTIVE','핵심 리스크는 기술 자체보다 실행에 있습니다.','The primary risk is execution rather than the technology itself.','the primary risk is...'],
 ['EXECUTIVE','완벽한 예측이 아니라 불확실성 속에서 더 나은 결정을 하는 것이 목표입니다.','The goal is not perfect prediction; it is making better decisions under uncertainty.','decisions under uncertainty'],
 ['EXECUTIVE','세 가지 선택지가 있지만 현재 증거를 기준으로 두 번째 안이 가장 합리적입니다.','We have three viable options. Based on the evidence available today, option two is the most defensible path.','the most defensible path']
];
const words=[
 ['TECHNICAL','pronounced fluctuation','뚜렷한 변동','We observed pronounced fluctuations during the second half of the cycle.'],
 ['TECHNICAL','rule out a possibility','가능성을 배제하다','We cannot rule out a sensor-related issue yet.'],
 ['TECHNICAL','narrow down the root cause','근본 원인의 범위를 좁히다','The next test should help us narrow down the root cause.'],
 ['BUSINESS','economic trade-off','경제적 상충관계','We should make the economic trade-off explicit before we decide.'],
 ['MBA','value creation','가치 창출','The question is whether this strategy creates durable value.'],
 ['MBA','sustainable competitive advantage','지속 가능한 경쟁우위','A durable advantage matters more than growth alone.'],
 ['LEADERSHIP','align on the objective','목표에 합의하다','Before discussing solutions, let us align on the objective.'],
 ['LEADERSHIP','surface the disagreement','의견 차이를 명확히 드러내다','I want to surface the disagreement before we move forward.'],
 ['EXECUTIVE','the most defensible path','가장 논리적으로 방어 가능한 방향','Given what we know today, this is the most defensible path.'],
 ['EXECUTIVE','decision under uncertainty','불확실성 속의 의사결정','Leadership often comes down to making good decisions under uncertainty.'],
 ['MBA','capital allocation','자본 배분','This is fundamentally a capital allocation decision.'],
 ['EXECUTIVE','protect the downside','하방 위험을 방어하다','We can pursue the upside while protecting the downside.']
];