'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const cp=require('child_process');const readline=require('readline');
const {DefaultArtifactClient}=require('@actions/artifact');
const artifact=new DefaultArtifactClient();const repo=process.env.GITHUB_REPOSITORY;const run=Number(process.env.GITHUB_RUN_ID);const token=process.env.GITHUB_TOKEN;const branch='chatgpt-v73-raw-recovery-20260930';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function files(root){let out=[];for(const x of fs.readdirSync(root,{withFileTypes:true})){const p=path.join(root,x.name);if(x.isDirectory())out.push(...files(p));else if(x.isFile())out.push(p);}return out;}
async function api(route,method='GET'){const r=await fetch('https://api.github.com/repos/'+repo+route,{method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(r.status===404)return null;if(r.status===204)return {};if(!r.ok)throw Error('GitHub API '+r.status+' '+route);return await r.json();}
async function waitAck(id,manifestHash){const p='/contents/research/v73_archive_scope/acks/'+run+'_'+id+'.json?ref='+encodeURIComponent(branch);const start=Date.now();while(Date.now()-start<90*60*1000){const o=await api(p);if(o&&o.content){const a=JSON.parse(Buffer.from(o.content,'base64').toString('utf8'));if(a.run_id!==run||a.artifact_id!==id||a.manifest_sha256!==manifestHash||a.verified!==true||!/^[0-9a-f]{64}$/.test(a.downloaded_zip_sha256||''))throw Error('invalid transfer acknowledgment');return a;}console.log('V73_WAITING_VERIFIED_TRANSFER '+JSON.stringify({run_id:run,artifact_id:id,manifest_sha256:manifestHash,wait_seconds:Math.floor((Date.now()-start)/1000)}));await sleep(30000);}throw Error('external transfer not acknowledged; artifact preserved and acquisition paused');}
async function main(){if(!token)throw Error('scoped workflow token missing');const p=cp.spawn('python3',['-u','research/v73_archive_scope/collect_archive.py'],{stdio:['pipe','pipe','inherit'],env:process.env});let childExit=null;const closed=new Promise(resolve=>p.once('close',(code,signal)=>{childExit={code,signal};resolve(childExit)}));
try{for await(const line of readline.createInterface({input:p.stdout})){console.log(line);if(!line.startsWith('V73_CHUNK '))continue;const c=JSON.parse(line.slice(10));const root=path.resolve(c.root);const expected=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'SHA256SUMS.json'))).digest('hex');if(expected!==c.manifest_sha256)throw Error('local chunk manifest mismatch');
const listing=await api('/actions/artifacts?per_page=100');const existing=(listing.artifacts||[]).filter(x=>!x.expired).reduce((n,x)=>n+x.size_in_bytes,0);const size=files(root).reduce((n,f)=>n+fs.statSync(f).size,0);if(existing+size>400*1024*1024)throw Error('conservative live artifact storage ceiling; chunk retained, no paid storage expansion');
const name='v73-pit-raw-'+run+'-'+String(c.chunk).padStart(4,'0');const uploaded=await artifact.uploadArtifact(name,files(root),root,{retentionDays:1,compressionLevel:0});if(!uploaded.id)throw Error('artifact upload did not return ID');console.log('V73_TRANSFER_READY '+JSON.stringify({run_id:run,artifact_id:uploaded.id,name,manifest_sha256:expected,records:c.records,archive_size:uploaded.size,final:c.final,progress:c.progress}));
const ack=await waitAck(uploaded.id,expected);const meta=await api('/actions/artifacts/'+uploaded.id);if(!meta||!meta.workflow_run||meta.workflow_run.id!==run||meta.name!==name)throw Error('artifact identity mismatch before temporary cleanup');if(meta.digest&&meta.digest!=='sha256:'+ack.downloaded_zip_sha256)throw Error('downloaded ZIP digest mismatch; artifact preserved');await api('/actions/artifacts/'+uploaded.id,'DELETE');console.log('V73_TRANSFER_ACKNOWLEDGED '+JSON.stringify({run_id:run,artifact_id:uploaded.id,temporary_remote_copy_deleted:true,verified_external_copy:ack.downloaded_zip_sha256}));p.stdin.write('CONTINUE\n');}
const result=await closed;if(result.code!==0)throw Error('collector exited '+JSON.stringify(result));
}catch(e){p.stdin.end();p.kill('SIGTERM');console.error('V73_DRIVER_STOP '+e.stack);process.exitCode=1;}
}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
